[[redirects]]
  from = "/api/*"
  to = "http://api.weatherapi.com/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[build]
  command = "npm run build"
  publish = "dist"